### ISSUE TITLE
Cannot fit into memory for {L=190, k=40} and {L=250, k=24}

### ISSUE THREAD

**Issue by zijunwei** [andreasveit/densenet-pytorch#3]
I used the DenseNet-BC architecture in Table 2 of the original paper. When I tried with {L=190, k=40} and {L=250, k=24}, the number of parameters seems to be correct (15.3M and 25.6M), but it doesn't fitin to a 12GB Titan X memory. The batchsize is 64.

Do you have the same problem? If not, could you give some possible reasons for causing this problem?
Thanks!

**Comment by andreasveit** [comment]
This seems expected. I think the authors trained their models on a machine with multiple (likely 4-8) GPUs and used the more memory efficient Caffe implementation.
