### ISSUE TITLE
Reproduce CIFAR-100 result

### ISSUE THREAD

**Issue by Jongchan** [andreasveit/densenet-pytorch#4]
Thank you for the great repository.

I wonder if you got the CIFAR-100 results as stated in the paper.

For example, DenseNet-BC(100, k=24) with 17.60% error on C100+
or DenseNet-BC(100, k=40) with 17.18% error on C100+

**Comment by andreasveit** [comment]
I have not run CIFAR-100. If you run it, please feel free to add the results.
